### ISSUE TITLE
Problema visual no "pesquisar" do VS Code

### ISSUE THREAD

**Issue by jorge-junio** [silv4b/silv4b-dark-theme#1]
Quando vai na opção de pesquisar do VS Code e seleciona o texto da barra de pesquisa não é possível ver que o texto está selecionado.

**Comment by silv4b** [comment]
Changes in:
"terminal.selectionBackground": "#00000040" to "terminal.selectionBackground": "#0066ff"
and
"selection.background": "#6082b600" to "selection.background": "#0066ff"
